name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: your_docker_image_name:latest
        build-args: OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}

    - name: Copy .htaccess file to container
      uses: docker/build-push-action@v2
      with:
        context: .
        target: builder
        args:
          HTTPD_CONF_PATH: /usr/local/apache2/conf/httpd.conf
        run: |
          echo "Include /var/www/html/.htaccess" >> $HTTPD_CONF_PATH
